
-- MySQL Script generated by MySQL Workbench
-- Tue Apr 18 01:36:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema biblioteca1_mvc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca1_mvc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca1_mvc` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `biblioteca1_mvc` ;

-- -----------------------------------------------------
-- Table `biblioteca1_mvc`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca1_mvc`.`autor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `autor` VARCHAR(150) NOT NULL,
  `imagen` VARCHAR(100) NOT NULL,
  `estado` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca1_mvc`.`configuracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca1_mvc`.`configuracion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `direccion` TEXT NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca1_mvc`.`editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca1_mvc`.`editorial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `editorial` VARCHAR(150) NOT NULL,
  `estado` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca1_mvc`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca1_mvc`.`estudiante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(20) NOT NULL,
  `dni` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `carrera` VARCHAR(255) NOT NULL,
  `direccion` TEXT NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `estado` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca1_mvc`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca1_mvc`.`libro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` TEXT NOT NULL,
  `cantidad` INT NOT NULL,
  `id_autor` INT NOT NULL,
  `id_editorial` INT NOT NULL,
  `anio_edicion` DATE NOT NULL,
  `id_materia` INT NOT NULL,
  `num_pagina` INT NOT NULL,
  `descripcion` TEXT NOT NULL,
  `imagen` VARCHAR(100) NOT NULL,
  `estado` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca1_mvc`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca1_mvc`.`materia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `materia` TEXT NOT NULL,
  `estado` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca1_mvc`.`membresia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca1_mvc`.`membresia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(200) NOT NULL,
  `precio` INT NULL DEFAULT NULL,
  `tipo` VARCHAR(200) NOT NULL,
  `estado` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca1_mvc`.`prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca1_mvc`.`prestamo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_estudiante` INT NOT NULL,
  `id_libro` INT NOT NULL,
  `fecha_prestamo` DATE NOT NULL,
  `fecha_devolucion` DATE NOT NULL,
  `cantidad` INT NOT NULL,
  `observacion` TEXT NOT NULL,
  `estado` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca1_mvc`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca1_mvc`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `clave` VARCHAR(100) NOT NULL,
  `rol` VARCHAR(20) NOT NULL,
  `estado` INT NOT NULL DEFAULT '1',
  `membresiaEstado` VARCHAR(20) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

/*IMPORTANTE*/
/*OJO OJO OJO*/

/*Agregar usuarios a la base de datos*/


INSERT INTO `usuarios` (`id`, `usuario`, `nombre`, `clave`, `rol`, `estado`, `membresiaEstado`) VALUES
(1, 'admin', 'Francisco Escoto', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', '1', 1,1),
(2, 'naju', 'Naju Vega ramirez', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', '2', 0,1),
(3, 'ana', 'ana', '24d4b96f58da6d4a8512313bbd02a28ebf0ca95dec6e4c86ef78ce7f01e788ac', '2', 1,1),
(4, 'maria', 'maria', '94aec9fbed989ece189a7e172c9cf41669050495152bc4c1dbf2a38d7fd85627', '1', 1,1);

/*usuario de administrador USUARIO: admin CONTRASEÑA:admin*/
/*usuario de empleado USUARIO: ana CONTRASEÑA:ana*/